language: php
services:
  - mysql
php:
  - 7.1
  - 7.2
  
before_install:
  - wget http://pecl.php.net/get/swoole-4.3.1.tgz
    && tar zfvx swoole-4.3.1.tgz
    && cd swoole-4.3.1
    && phpize
    && ./configure
    && make
    && sudo make install
    && cd ..
  - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('110') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  
before_script:
  - composer install --dev
  - cd tests
script: 
  - ../vendor/bin/phpunit -v
after_script:
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v
